"""
ORCA-specific functionality for the Multi-Agent DFT Research System.
"""

import os
import logging
from pathlib import Path
import numpy as np

logger = logging.getLogger(__name__)

class ORCAInterface:
    """Interface for generating ORCA input files and analyzing ORCA outputs."""

    def __init__(self, config=None):
        """
        Initialize the ORCA interface with optional configuration.

        Args:
            config (dict, optional): Configuration parameters for ORCA calculations.
        """
        self.config = config or {}
        self.default_config = {
            'method': 'B3LYP',
            'basis_set': 'def2-TZVP',
            'aux_basis': 'def2/J',  # Auxiliary basis for RI approximation
            'job_type': 'Opt',
            'charge': 0,
            'multiplicity': 1,
            'nprocs': 4,
            'maxcore': 2000,  # MB per core
            'scf_convergence': 'TightSCF',
            'grid': 'DefGrid2'
        }

    def get_config(self):
        """
        Get the effective configuration by merging default with user config.

        Returns:
            dict: Effective configuration.
        """
        effective_config = self.default_config.copy()
        effective_config.update(self.config)
        return effective_config

    def generate_input(self, structure_data, output_file=None, custom_config=None):
        """
        Generate an ORCA input file from structure data.

        Args:
            structure_data (dict): Structure data with atom coordinates and metadata.
            output_file (str or Path, optional): Path to save the input file.
            custom_config (dict, optional): Custom configuration for this specific job.

        Returns:
            str: ORCA input file content.
        """
        # Merge configs
        config = self.get_config()
        if custom_config:
            config.update(custom_config)

        # Build the ORCA input file
        orca_lines = []

        # Comment line (optional)
        orca_lines.append(f"# ORCA input file generated by Multi-Agent DFT System")
        orca_lines.append("")

        # Main input line - Simple input section
        input_keywords = []

        # Method and basis set
        method = config.get('method', 'B3LYP')
        basis = config.get('basis_set', 'def2-TZVP')
        input_keywords.append(method)
        input_keywords.append(basis)

        # Job type
        job_type = config.get('job_type', 'Opt')
        if job_type.upper() not in ['SP', 'ENERGY']:
            input_keywords.append(job_type)

        # RI approximation (common for DFT)
        if config.get('use_ri', True):
            input_keywords.append('RI')
            aux_basis = config.get('aux_basis', 'def2/J')
            input_keywords.append(aux_basis)

        # SCF convergence
        scf_conv = config.get('scf_convergence', 'TightSCF')
        input_keywords.append(scf_conv)

        # Grid quality
        grid = config.get('grid', 'DefGrid2')
        input_keywords.append(grid)

        # Dispersion correction
        if 'dispersion' in config:
            disp = config['dispersion']
            if disp.upper() in ['D3', 'D3BJ', 'D4']:
                input_keywords.append(disp.upper())

        # Add solvation model if specified
        if 'solvent' in config:
            solvent = config['solvent']
            solvent_model = config.get('solvent_model', 'CPCM')
            input_keywords.append(f"{solvent_model}({solvent})")

        # Parallelization
        nprocs = config.get('nprocs', 4)
        input_keywords.append(f"PAL{nprocs}")

        # Build the main input line
        orca_lines.append(f"! {' '.join(input_keywords)}")
        orca_lines.append("")

        # MaxCore specification
        maxcore = config.get('maxcore', 2000)
        orca_lines.append(f"%maxcore {maxcore}")
        orca_lines.append("")

        # SCF block for additional settings
        if 'max_iterations' in config or 'direct_reset' in config:
            orca_lines.append("%scf")
            if 'max_iterations' in config:
                orca_lines.append(f"  MaxIter {config['max_iterations']}")
            if config.get('direct_reset', False):
                orca_lines.append("  DirectResetFreq 1")
            orca_lines.append("end")
            orca_lines.append("")

        # Geometry optimization settings
        if job_type.upper() in ['OPT', 'OPTTS', 'COPT']:
            orca_lines.append("%geom")
            if 'max_opt_iterations' in config:
                orca_lines.append(f"  MaxIter {config['max_opt_iterations']}")
            if 'opt_convergence' in config:
                conv = config['opt_convergence'].upper()
                if conv in ['LOOSE', 'NORMAL', 'TIGHT', 'VERYTIGHT']:
                    orca_lines.append(f"  {conv}Opt")
            orca_lines.append("end")
            orca_lines.append("")

        # Frequency calculation settings
        if 'Freq' in job_type or 'frequency' in config.get('job_type', '').lower():
            orca_lines.append("%freq")
            if config.get('numerical_freq', False):
                orca_lines.append("  CentralDiff true")
            orca_lines.append("end")
            orca_lines.append("")

        # Molecular mechanics settings (if QM/MM)
        if 'qmmm' in config:
            orca_lines.append("%qmmm")
            # Add QM/MM specific settings here
            orca_lines.append("end")
            orca_lines.append("")

        # Coordinate specification
        charge = config.get('charge', 0)
        mult = config.get('multiplicity', 1)

        orca_lines.append(f"* xyz {charge} {mult}")

        # Add atomic coordinates
        if 'coordinates' in structure_data:
            for coord in structure_data['coordinates']:
                element = coord.get('element', coord.get('atom_type', 'X'))
                x = coord.get('x', 0.0)
                y = coord.get('y', 0.0)
                z = coord.get('z', 0.0)
                orca_lines.append(f"  {element:2s}  {x:12.8f}  {y:12.8f}  {z:12.8f}")
        elif 'atoms' in structure_data:
            for atom in structure_data['atoms']:
                element = atom.get('element', atom.get('symbol', 'X'))
                pos = atom.get('position', [0.0, 0.0, 0.0])
                orca_lines.append(f"  {element:2s}  {pos[0]:12.8f}  {pos[1]:12.8f}  {pos[2]:12.8f}")

        orca_lines.append("*")
        orca_lines.append("")

        input_content = "\n".join(orca_lines)

        # Save to file if requested
        if output_file:
            output_path = Path(output_file)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            with open(output_path, 'w') as f:
                f.write(input_content)
            logger.info(f"ORCA input file written to {output_path}")
            return True

        return input_content


def save_orca_input(structure_data, output_file, config=None):
    """
    Convenience function to save an ORCA input file.

    Args:
        structure_data (dict): Structure data with atom coordinates and metadata.
        output_file (str or Path): Path to save the input file.
        config (dict, optional): Configuration parameters for ORCA.

    Returns:
        bool: Success status.
    """
    interface = ORCAInterface(config)
    return interface.generate_input(structure_data, output_file)
